
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: default
spec:
  selector:
    app: node-exporter
  ports:
    - port: 9100
      targetPort: 9100
  clusterIP: None
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: default
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostPID: true
      containers:
      - name: node-exporter
        image: prom/node-exporter:v1.8.1
        ports:
        - containerPort: 9100
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        args:
          - --path.procfs=/host/proc
          - --path.sysfs=/host/sys
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys


#hello 