# Prometheus ConfigMap with static scrape configs
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-services'
        static_configs:
          - targets:
            - 'ai-cheatsheet-maker.default.svc.cluster.local:5000'
            - 'notes-service.default.svc.cluster.local:5002'
            - 'todo-service.default.svc.cluster.local:5001'
            - 'user-service.default.svc.cluster.local:5000'
