# Prometheus ConfigMap with static scrape configs
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-services'
        static_configs:
          - targets:
            - 'ai-cheatsheet-maker:80'
            - 'notes-service:80'
            - 'todo-service:80'
            - 'user-service:80'
            - 'frontend:80'
