name: Deploy Apps and Secrets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Make scripts executable
        run: |
          chmod +x ./scripts/clone-org.sh
          
      - name: Clone all repos
        run: ./scripts/clone-org.sh
        
      - name: Create Kubernetes secret for AWS credentials
        run: |
          kubectl delete secret bedrock-secrets --ignore-not-found=true
          kubectl create secret generic bedrock-secrets \
            --from-literal=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --from-literal=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --from-literal=AWS_DEFAULT_REGION=us-east-1
            
      - name: Deploy all Kubernetes manifests
        run: |
          find ./polyglot-org -name '*.yaml' -not -path '*/.github/*' \
            -exec kubectl apply -f {} \;
