# .github/workflows/run-scripts.yml
name: Run K8s Setup Scripts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-setup:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: |
          chmod +x ./scripts/clone-org.sh
          chmod +x ./scripts/kubeadm-init.sh

      - name: Run script to clone repositories
        run: ./scripts/clone-org.sh

   #   - name: Run script to set up Kubernetes
    #    run: ./scripts/kubeadm-init.sh

      - name: Deploy all Kubernetes manifests
        run: |
          kubectl apply -f polyglot-org/ -R
